name: hive_tutorial
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  hive: ^2.0.6
  hive_flutter: 1.1.0
  hive_generator: ^1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

